<?php return array (
  'sans-serif' => array(
    'normal' => $rootDir . '\lib\fonts\Helvetica',
    'bold' => $rootDir . '\lib\fonts\Helvetica-Bold',
    'italic' => $rootDir . '\lib\fonts\Helvetica-Oblique',
    'bold_italic' => $rootDir . '\lib\fonts\Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $rootDir . '\lib\fonts\Times-Roman',
    'bold' => $rootDir . '\lib\fonts\Times-Bold',
    'italic' => $rootDir . '\lib\fonts\Times-Italic',
    'bold_italic' => $rootDir . '\lib\fonts\Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $rootDir . '\lib\fonts\Times-Roman',
    'bold' => $rootDir . '\lib\fonts\Times-Bold',
    'italic' => $rootDir . '\lib\fonts\Times-Italic',
    'bold_italic' => $rootDir . '\lib\fonts\Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $rootDir . '\lib\fonts\Courier',
    'bold' => $rootDir . '\lib\fonts\Courier-Bold',
    'italic' => $rootDir . '\lib\fonts\Courier-Oblique',
    'bold_italic' => $rootDir . '\lib\fonts\Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $rootDir . '\lib\fonts\Helvetica',
    'bold' => $rootDir . '\lib\fonts\Helvetica-Bold',
    'italic' => $rootDir . '\lib\fonts\Helvetica-Oblique',
    'bold_italic' => $rootDir . '\lib\fonts\Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $rootDir . '\lib\fonts\ZapfDingbats',
    'bold' => $rootDir . '\lib\fonts\ZapfDingbats',
    'italic' => $rootDir . '\lib\fonts\ZapfDingbats',
    'bold_italic' => $rootDir . '\lib\fonts\ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $rootDir . '\lib\fonts\Symbol',
    'bold' => $rootDir . '\lib\fonts\Symbol',
    'italic' => $rootDir . '\lib\fonts\Symbol',
    'bold_italic' => $rootDir . '\lib\fonts\Symbol',
  ),
  'serif' => array(
    'normal' => $rootDir . '\lib\fonts\Times-Roman',
    'bold' => $rootDir . '\lib\fonts\Times-Bold',
    'italic' => $rootDir . '\lib\fonts\Times-Italic',
    'bold_italic' => $rootDir . '\lib\fonts\Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $rootDir . '\lib\fonts\Courier',
    'bold' => $rootDir . '\lib\fonts\Courier-Bold',
    'italic' => $rootDir . '\lib\fonts\Courier-Oblique',
    'bold_italic' => $rootDir . '\lib\fonts\Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $rootDir . '\lib\fonts\Courier',
    'bold' => $rootDir . '\lib\fonts\Courier-Bold',
    'italic' => $rootDir . '\lib\fonts\Courier-Oblique',
    'bold_italic' => $rootDir . '\lib\fonts\Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $rootDir . '\lib\fonts\DejaVuSans-Bold',
    'bold_italic' => $rootDir . '\lib\fonts\DejaVuSans-BoldOblique',
    'italic' => $rootDir . '\lib\fonts\DejaVuSans-Oblique',
    'normal' => $rootDir . '\lib\fonts\DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $rootDir . '\lib\fonts\DejaVuSansMono-Bold',
    'bold_italic' => $rootDir . '\lib\fonts\DejaVuSansMono-BoldOblique',
    'italic' => $rootDir . '\lib\fonts\DejaVuSansMono-Oblique',
    'normal' => $rootDir . '\lib\fonts\DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $rootDir . '\lib\fonts\DejaVuSerif-Bold',
    'bold_italic' => $rootDir . '\lib\fonts\DejaVuSerif-BoldItalic',
    'italic' => $rootDir . '\lib\fonts\DejaVuSerif-Italic',
    'normal' => $rootDir . '\lib\fonts\DejaVuSerif',
  ),
  'poppins' => array(
    'normal' => $fontDir . '/poppins-normal_1e5f0a9840a7851e471d32b2a69235dd',
    'italic' => $fontDir . '/poppins-italic_7e849b7a14602e70cb7099c5140530dd',
    '100' => $fontDir . '/poppins-100_48e61cfc97c0e9e013bb2773276d2095',
    '200' => $fontDir . '/poppins-200_83b8c3baa3cb9873b09381845487698b',
    '200_italic' => $fontDir . '/poppins-200-italic_bfb28a8157bb387fc6cbc921ffc1d318',
    '100_italic' => $fontDir . '/poppins-100-italic_1f74c81c1c7e5108c24a14598c30de03',
    '300' => $fontDir . '/poppins-300_f07243a8f00891ec2849cdb8c61d52bf',
    '300_italic' => $fontDir . '/poppins-300-italic_fb6979fe6d1762bd0342b6c2d45dae3b',
    '500' => $fontDir . '/poppins-500_f064918b1a10190f682d0709b588b370',
    '500_italic' => $fontDir . '/poppins-500-italic_c8801791648f6e6e0e61658d9ac0c219',
    '600' => $fontDir . '/poppins-600_8c294430a6fbb09a408db84c91c4459b',
    '600_italic' => $fontDir . '/poppins-600-italic_ddcd13998fd5937f71a46f68be3f8282',
    'bold' => $fontDir . '/poppins-bold_580514dc045fca89edfb6de8c138e028',
    'bold_italic' => $fontDir . '/poppins-bold-italic_63aaa7f9cdd344b46655fbd23d35938d',
    '800' => $fontDir . '/poppins-800_29966f46c43a10ac696bd4f94da40aeb',
    '800_italic' => $fontDir . '/poppins-800-italic_94ca884f4208bcc92a3c3936f92750fe',
    '900' => $fontDir . '/poppins-900_55b43907f93a3eb82303d278bc21d5f1',
    '900_italic' => $fontDir . '/poppins-900-italic_f508852680ca31e9df53d78d3b7cbf43',
  ),
  'alamain' => array(
    'normal' => $fontDir . '/alamain-normal_8b0dee0d5e574fb66385e9602060f599',
  ),
) ?>