<?php return array (
  'sans-serif' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold' => $rootDir . '/lib/fonts/ZapfDingbats',
    'italic' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold_italic' => $rootDir . '/lib/fonts/ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $rootDir . '/lib/fonts/Symbol',
    'bold' => $rootDir . '/lib/fonts/Symbol',
    'italic' => $rootDir . '/lib/fonts/Symbol',
    'bold_italic' => $rootDir . '/lib/fonts/Symbol',
  ),
  'serif' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSans-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSans-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSans-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSansMono-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSansMono-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSansMono-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSerif-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSerif-BoldItalic',
    'italic' => $rootDir . '/lib/fonts/DejaVuSerif-Italic',
    'normal' => $rootDir . '/lib/fonts/DejaVuSerif',
  ),
  'poppins' => array(
    '100' => $fontDir . '/poppins-100_27495269a7b9e056daadcfbcb7410945',
    '200' => $fontDir . '/poppins-200_950bc124cccc8294fbc1a88fd566a918',
    '200_italic' => $fontDir . '/poppins-200-italic_5a2780ef8ce2c95e6a3484dac72b2397',
    '100_italic' => $fontDir . '/poppins-100-italic_a53e74028b9aac92f989336eed8aceea',
    '300' => $fontDir . '/poppins-300_552ebe0a7087be352eecda77735d49dc',
    '300_italic' => $fontDir . '/poppins-300-italic_7be5be5f3c0b6790a83cf5426ab2b510',
    'normal' => $fontDir . '/poppins-normal_72fef4a726e08890edfe95b6c9e2f986',
    'italic' => $fontDir . '/poppins-italic_f5b756bec5e46386f6780e2526191d9a',
    '500' => $fontDir . '/poppins-500_7ceb0c78897c599984a5143d6fd7726e',
    '500_italic' => $fontDir . '/poppins-500-italic_145034050b9b4ae3e79e1300f2c992b8',
    '600' => $fontDir . '/poppins-600_c7a5ed87b6881da0490b4d9b08aaf7a6',
    '600_italic' => $fontDir . '/poppins-600-italic_65fae3087f48a717b75bb6585e03c81f',
    'bold' => $fontDir . '/poppins-bold_cba12a7639e44e7935d47c94de1c72d1',
    'bold_italic' => $fontDir . '/poppins-bold-italic_0df19edd5701f4dfc3b8f1d3b67a2bc1',
    '800' => $fontDir . '/poppins-800_f8dd273d8e6d18ea1cc517624f456300',
    '800_italic' => $fontDir . '/poppins-800-italic_b83241d59a48124537c44bf5b8ad8575',
    '900' => $fontDir . '/poppins-900_88ccb0692427368c62e5e2e572d958ac',
    '900_italic' => $fontDir . '/poppins-900-italic_105dc3c0db5a3e57e5d3fc0e13787113',
  ),
  'alamain' => array(
    'normal' => $fontDir . '/alamain-normal_a5d9619b8f4fe8f519b0195d16d88dcc',
  ),
) ?>